
import jax.numpy as jnp
import numpy as np
from sympy import Matrix, lambdify, sqrt

from biosym.model.contact.base_contact import BaseContact


class HuntCrossley(BaseContact):
    """
    Hunt-Crossley contact, as in OpenSim/Simbody, in a smoothed (collocation-
    friendly) form.
    This class models the forces generated by simple point contacts, 
    such as between two spheres, or a sphere and a half space.
    This includes components for the normal restoring force, 
    dissipation in the material, and surface friction. 
    This force is only applied to point contacts. 
    Other contacts, such as those involving triangle meshes, are ignored.

    Normal force (Hertzian elastic + Hunt-Crossley dissipation):
        f_n = k * x_+^(3/2) * (1 + (3/2) * c * xdot)
    x is penetration depth, xdot its rate, k the stiffness (used as-is: the
    OpenSim value is already a physical k, NOT body-weight scaled), c the
    dissipation. x_+ is a smoothed positive part of x so the law switches
    on/off differentiably.

    Friction (smoothed three-coefficient model):
        F_f = -f_n * [ blend * vt / sqrt(|vt|^2 + v_t^2) + uv * vt ]
        blend = ud + 2 (us - ud) / (1 + |vt|^2 / v_t^2)
    static (us) blending to dynamic (ud) with slip, plus viscous (uv). The
    OpenSim min(vs/vt, 1) ramp is replaced by the smooth
    vt / sqrt(|vt|^2 + v_t^2) for differentiability.

    Parameters map directly onto the OSIM HuntCrossleyForce_ContactParameters
    (stiffness, dissipation, static/dynamic/viscous_friction, transition_velocity).

    Parameters are hardcoded into the symbolic expression, so this law adds no
    states and no constants to the optimization.
    """

    def __init__(self, pairs, stiffness, dissipation,
                 static_friction, dynamic_friction, viscous_friction,
                 transition_velocity=0.01, eps_depth=1e-4, **kwargs):
        super().__init__(pairs, **kwargs)
        self.k = float(stiffness)
        self.c = float(dissipation)
        self.us = float(static_friction)
        self.ud = float(dynamic_friction)
        self.uv = float(viscous_friction)
        self.v_t = float(transition_velocity)
        self.eps_depth = float(eps_depth)

    # ------------------------------------------------------------------
    # States / constants: all parameters hardcoded.
    # ------------------------------------------------------------------
    def get_n_states(self):
        return 0

    def get_n_constants(self):
        return 0

    def get_states(self):
        return []

    def get_constants(self):
        return []

    # ------------------------------------------------------------------
    # The Hunt-Crossley per-pair force formula.
    # ------------------------------------------------------------------
    def _pair_force(self, pen):
        """Symbolic (3, 1) contact force on the feature, from one penetration
        dict. The reaction on `other` is added by process_eom."""
        x = pen["depth"]
        xdot = pen["normal_velocity"]
        normal = pen["normal"]               # (3, 1) outward unit normal
        vt = pen["tangential_velocity"]      # (3, 1) slip velocity

        # Smooth positive depth: ~x when penetrating, ~0 when clear.
        x_pos = 0.5 * (sqrt(x ** 2 + self.eps_depth ** 2) + x)

        # Hertzian elastic term with Hunt-Crossley dissipation.
        f_n = self.k * x_pos ** 1.5 * (1 + 1.5 * self.c * xdot)
        force_normal = f_n * normal

        # Smoothed static/dynamic Coulomb blend + viscous friction.
        v_s_sq = vt.dot(vt)
        blend = self.ud + 2 * (self.us - self.ud) / (1 + v_s_sq / self.v_t ** 2)
        coulomb = blend * vt / sqrt(v_s_sq + self.v_t ** 2)
        viscous = self.uv * vt
        force_friction = -f_n * (coulomb + viscous)

        return force_normal + force_friction

    # ------------------------------------------------------------------
    # Symbolic assembly.
    # ------------------------------------------------------------------
    def process_eom(self, model, **kwargs):
        self._build_geometries(model)

        body_keys = list(model.rigid_bodies.keys())
        force_exprs, pos_exprs = [], []
        contrib_body_slot, contrib_fk_idx = [], []

        def _add_contribution(force_expr, geometry):
            force_exprs.append(force_expr)
            pos_exprs.append(geometry.pos_expr)
            contrib_body_slot.append(self._body_index(geometry.parent_body))
            contrib_fk_idx.append(body_keys.index(geometry.parent_body))

        for feature, other in self.pairs:
            pen = feature.penetration(other)
            force_on_feature = self._pair_force(pen)

            _add_contribution(force_on_feature, feature)
            # Newton's third law on a real-body `other` (a ground half-space
            # has no force slot, so its reaction is dropped).
            if other.parent_body != "ground_frame":
                _add_contribution(-force_on_feature, other)

        # One fused lambdify each (CSE across all contributions). Each row is
        # one contribution's (x, y, z).
        force_matrix = Matrix.vstack(*[f.T for f in force_exprs])
        pos_matrix = Matrix.vstack(*[p.T for p in pos_exprs])
        self.force_fn = lambdify(model._v, force_matrix, modules="jax", cse=True, docstring_limit=2)
        self.pos_fn = lambdify(model._v, pos_matrix, modules="jax", cse=True, docstring_limit=2)

        self._contrib_body_slot = np.array(contrib_body_slot)
        self._contrib_fk_idx = np.array(contrib_fk_idx)

    # ------------------------------------------------------------------
    # Numeric evaluation (pure JAX -- differentiated & jitted upstream).
    # ------------------------------------------------------------------
    def forward(self, states, constants, model):
        forces = self.force_fn(*states.model, *constants.model)     # (n_contrib, 3)
        positions = self.pos_fn(*states.model, *constants.model)    # (n_contrib, 3)

        body_positions = model.run["FK"](states, constants)[self._contrib_fk_idx]
        moment_arms = positions - body_positions
        moments = jnp.cross(moment_arms, forces)

        body_forces = self._aggregate_to_bodies(forces, self._contrib_body_slot)
        body_moments = self._aggregate_to_bodies(moments, self._contrib_body_slot)
        return body_forces, body_moments

    def reset(self):
        pass

    # ------------------------------------------------------------------
    # Basic visualization: each contribution's point + force arrow.
    # ------------------------------------------------------------------
    def plot(self, states, model, mode, ax, **kwargs):
        s, c = states.states, states.constants
        positions = np.asarray(self.pos_fn(*s.model, *c.model))
        forces = np.asarray(self.force_fn(*s.model, *c.model))
        factor = kwargs.get("force_scale", 1e-3)

        if mode == "init":
            self._plot_markers, self._plot_force_lines = [], []
            for i in range(positions.shape[0]):
                (m,) = ax.plot([positions[i, 0]], [positions[i, 1]], [positions[i, 2]],
                               c="k", marker="o")
                tip = positions[i] + factor * forces[i]
                (fl,) = ax.plot([positions[i, 0], tip[0]],
                                [positions[i, 1], tip[1]],
                                [positions[i, 2], tip[2]], c="darkgreen")
                self._plot_markers.append(m)
                self._plot_force_lines.append(fl)
            return self._plot_markers, self._plot_force_lines

        if mode == "update":
            for i, (m, fl) in enumerate(zip(self._plot_markers, self._plot_force_lines)):
                m.set_data([positions[i, 0]], [positions[i, 1]])
                m.set_3d_properties(positions[i, 2])
                tip = positions[i] + factor * forces[i]
                fl.set_data([positions[i, 0], tip[0]], [positions[i, 1], tip[1]])
                fl.set_3d_properties([positions[i, 2], tip[2]])
            return

        raise ValueError("Invalid mode. Must be 'init' or 'update'.")