
import jax.numpy as jnp
import numpy as np
from sympy import Matrix, lambdify, sqrt

from biosym.model.contact.base_contact import BaseContact


class HuntCrossley(BaseContact):
    """
    Hunt-Crossley contact, as in OpenSim/Simbody, in a smoothed (collocation-
    friendly) form.
    This class models the forces generated by simple point contacts, 
    such as between two spheres, or a sphere and a half space.
    This includes components for the normal restoring force, 
    dissipation in the material, and surface friction. 
    This force is only applied to point contacts. 
    Other contacts, such as those involving triangle meshes, are ignored.

    Normal force (Hertzian elastic + Hunt-Crossley dissipation):
        f_n = k * x_+^(3/2) * diss_+ + grad_bias * x
        diss = 1 + (3/2) * c * xdot
    x is penetration depth, xdot its rate, k the stiffness (used as-is: the
    OpenSim value is already a physical k, NOT body-weight scaled), c the
    dissipation. x_+ is a smoothed positive part of x so the law switches
    on/off differentiably. diss_+ is likewise a smoothed positive part of the
    dissipation factor: raw Hunt-Crossley lets diss go negative during fast
    separation (xdot very negative), which flips f_n attractive/negative right
    at liftoff and is a known source of jitter in gradient-based collocation --
    the reference BioMAC-Sim-Toolbox gait3d_smoothsphere contact (generated via
    SymPy, github.com/mad-lab-fau/BioMAC-Sim-Toolbox, opensimContactModel
    branch) guards against exactly this with an equivalent smooth clamp. The
    grad_bias * x term is a small linear-in-raw-depth bias (legacy "point
    towards ground" term) that keeps a nonzero force gradient even where the
    smoothed x_+ has flattened out away from contact.

    Friction (smoothed three-coefficient model):
        F_f = -f_n * [ blend * vt / sqrt(|vt|^2 + v_t^2) + uv * vt ]
        blend = ud + 2 (us - ud) / (1 + |vt|^2 / v_t^2)
    static (us) blending to dynamic (ud) with slip, plus viscous (uv). The
    OpenSim min(vs/vt, 1) ramp is replaced by the smooth
    vt / sqrt(|vt|^2 + v_t^2) for differentiability.

    Parameters map directly onto the OSIM HuntCrossleyForce_ContactParameters
    (stiffness, dissipation, static/dynamic/viscous_friction, transition_velocity).
    The values in gait2d_ground_contact_huntcrossley.xml match the
    SmoothSphereHalfSpaceForce parameters of Falisse et al. 2022's OpenSim
    model (PLoS ONE 17(1):e0256311, per
    Subjects/Falisse_et_al_2022/Falisse_et_al_2022.osim in
    github.com/KULeuvenNeuromechanics/PredSim), the contact formulation
    Afschrift et al. 2025 builds on.

    Parameters are hardcoded into the symbolic expression, so this law adds no
    states and no constants to the optimization.
    """

    def __init__(self, pairs, stiffness, dissipation,
                 static_friction, dynamic_friction, viscous_friction,
                 transition_velocity=0.01, eps_depth=1e-4, eps_diss=5e-2,
                 grad_bias=1e-1, **kwargs):
        super().__init__(pairs, **kwargs)
        self.k = float(stiffness)
        self.c = float(dissipation)
        self.us = float(static_friction)
        self.ud = float(dynamic_friction)
        self.uv = float(viscous_friction)
        self.v_t = float(transition_velocity)
        self.eps_depth = float(eps_depth)
        self.eps_diss = float(eps_diss)
        self.grad_bias = float(grad_bias)

    # ------------------------------------------------------------------
    # States / constants: all parameters hardcoded.
    # ------------------------------------------------------------------
    def get_n_states(self):
        return 0

    def get_n_constants(self):
        return 0

    def get_states(self):
        return []

    def get_constants(self):
        return []

    # ------------------------------------------------------------------
    # The Hunt-Crossley per-pair force formula.
    # ------------------------------------------------------------------
    def _pair_force(self, pen):
        """Symbolic (3, 1) contact force on the feature, from one penetration
        dict. The reaction on `other` is added by process_eom."""
        x = pen["depth"]
        xdot = pen["normal_velocity"]
        normal = pen["normal"]               # (3, 1) outward unit normal
        vt = pen["tangential_velocity"]      # (3, 1) slip velocity

        # Smooth positive depth: ~x when penetrating, ~0 when clear.
        x_pos = 0.5 * (sqrt(x ** 2 + self.eps_depth ** 2) + x)

        # Hertzian elastic term with Hunt-Crossley dissipation, plus a small
        # bias linear in raw (unsmoothed) depth so a nonzero gradient toward
        # contact survives even where x_pos has flattened out to ~0 (legacy
        # "point towards ground" term). The dissipation factor is smoothly
        # clamped to be non-negative (same trick as x_pos) so fast separation
        # (xdot very negative) can't flip f_n attractive -- unclamped, this is
        # a known Hunt-Crossley non-negativity issue that shows up as jitter.
        diss = 1 + 1.5 * self.c * xdot
        diss_pos = 0.5 * (sqrt(diss ** 2 + self.eps_diss ** 2) + diss)
        f_n = self.k * x_pos ** 1.5 * diss_pos + self.grad_bias * x
        force_normal = f_n * normal

        # Smoothed static/dynamic Coulomb blend + viscous friction.
        v_s_sq = vt.dot(vt)
        blend = self.ud + 2 * (self.us - self.ud) / (1 + v_s_sq / self.v_t ** 2)
        coulomb = blend * vt / sqrt(v_s_sq + self.v_t ** 2)
        viscous = self.uv * vt
        force_friction = -f_n * (coulomb + viscous)

        return force_normal + force_friction

    # ------------------------------------------------------------------
    # Symbolic assembly.
    # ------------------------------------------------------------------
    def process_eom(self, model, **kwargs):
        self._build_geometries(model)

        body_keys = list(model.rigid_bodies.keys())
        force_exprs, pos_exprs = [], []
        contrib_body_slot, contrib_fk_idx = [], []

        def _add_contribution(force_expr, geometry):
            force_exprs.append(force_expr)
            pos_exprs.append(geometry.pos_expr)
            contrib_body_slot.append(self._body_index(geometry.parent_body))
            contrib_fk_idx.append(body_keys.index(geometry.parent_body))

        for feature, other in self.pairs:
            pen = feature.penetration(other)
            force_on_feature = self._pair_force(pen)

            _add_contribution(force_on_feature, feature)
            # Newton's third law on a real-body `other` (a ground half-space
            # has no force slot, so its reaction is dropped).
            if other.parent_body != "ground_frame":
                _add_contribution(-force_on_feature, other)

        # One fused lambdify each (CSE across all contributions). Each row is
        # one contribution's (x, y, z).
        force_matrix = Matrix.vstack(*[f.T for f in force_exprs])
        pos_matrix = Matrix.vstack(*[p.T for p in pos_exprs])
        self.force_fn = lambdify(model._symbols, force_matrix, modules="jax", cse=True, docstring_limit=2)
        self.pos_fn = lambdify(model._symbols, pos_matrix, modules="jax", cse=True, docstring_limit=2)

        self._contrib_body_slot = np.array(contrib_body_slot)
        self._contrib_fk_idx = np.array(contrib_fk_idx)

    # ------------------------------------------------------------------
    # Numeric evaluation (pure JAX -- differentiated & jitted upstream).
    # ------------------------------------------------------------------
    def forward(self, states, constants, model):
        s_flat = states.filter('model').flatten()
        c_flat = constants.filter('model').flatten()
        forces = self.force_fn(*s_flat, *c_flat)     # (n_contrib, 3)
        positions = self.pos_fn(*s_flat, *c_flat)    # (n_contrib, 3)

        body_positions = model.run["FK"](states, constants)[self._contrib_fk_idx]
        moment_arms = positions - body_positions
        moments = jnp.cross(moment_arms, forces)

        body_forces = self._aggregate_to_bodies(forces, self._contrib_body_slot)
        body_moments = self._aggregate_to_bodies(moments, self._contrib_body_slot)
        return body_forces, body_moments

    def reset(self):
        pass

    # ------------------------------------------------------------------
    # Basic visualization: each contribution's point + force arrow.
    # ------------------------------------------------------------------
    def plot(self, states, model, mode, ax, **kwargs):
        factor = kwargs.get("force_scale", 1e-3)
        case = kwargs.get("case", "3D")
        non_zero_axes = kwargs.get("non_zero_axes", [0, 1])
        frame = kwargs.get("frame", 0)

        if mode == "init":
            # Store the full sequence + constants so update can slice by frame
            # (update is called with states=False).
            s = states.states if hasattr(states, "states") else states
            c = states.constants if hasattr(states, "constants") else model.default_constants
            self._plot_states = s
            self._plot_constants = c

        # Pick one frame from the stored sequence.
        s = self._plot_states
        c = self._plot_constants
        s_frame = s[frame] if np.asarray(s.q).ndim > 1 else s

        s_flat = s_frame.filter('model').flatten()
        c_flat = c.filter('model').flatten()
        positions = np.asarray(self.pos_fn(*s_flat, *c_flat))
        forces = np.asarray(self.force_fn(*s_flat, *c_flat))
        body_positions = np.asarray(model.run["FK"](s_frame, c))[self._contrib_fk_idx]

        if mode == "init":
            self._plot_markers, self._plot_force_lines = [], []
            for i in range(positions.shape[0]):
                tip = positions[i] + factor * forces[i]
                if case == "2D":
                    a0, a1 = non_zero_axes
                    (m,) = ax.plot([positions[i, a0]], [positions[i, a1]], c="k", marker="o")
                    (fl,) = ax.plot([positions[i, a0], tip[a0]],
                                    [positions[i, a1], tip[a1]], c="darkgreen")
                else:
                    (m,) = ax.plot([positions[i, 0]], [positions[i, 1]], [positions[i, 2]],
                                   c="k", marker="o")
                    (fl,) = ax.plot([positions[i, 0], tip[0]],
                                    [positions[i, 1], tip[1]],
                                    [positions[i, 2], tip[2]], c="darkgreen")
                self._plot_markers.append(m)
                self._plot_force_lines.append(fl)

            # Link each contact point to its parent body (e.g. ankle).
            self._plot_body_lines = []
            for i in range(positions.shape[0]):
                if case == "2D":
                    a0, a1 = non_zero_axes
                    (bl,) = ax.plot([body_positions[i, a0], positions[i, a0]],
                                    [body_positions[i, a1], positions[i, a1]], c="k")
                else:
                    (bl,) = ax.plot([body_positions[i, 0], positions[i, 0]],
                                     [body_positions[i, 1], positions[i, 1]],
                                     [body_positions[i, 2], positions[i, 2]], c="k")
                self._plot_body_lines.append(bl)

            # Link contact points that share the same parent body (e.g. heel/toe).
            self._plot_cp_lines, self._cp_line_pairs = [], []
            for i in range(positions.shape[0]):
                for j in range(i + 1, positions.shape[0]):
                    if self._contrib_body_slot[i] != self._contrib_body_slot[j]:
                        continue
                    if case == "2D":
                        a0, a1 = non_zero_axes
                        (cl,) = ax.plot([positions[i, a0], positions[j, a0]],
                                        [positions[i, a1], positions[j, a1]], c="k")
                    else:
                        (cl,) = ax.plot([positions[i, 0], positions[j, 0]],
                                        [positions[i, 1], positions[j, 1]],
                                        [positions[i, 2], positions[j, 2]], c="k")
                    self._plot_cp_lines.append(cl)
                    self._cp_line_pairs.append((i, j))

            # Static ground floor at y=0, spanning the current view.
            if case == "2D":
                ax.fill_between(ax.get_xlim(), min(ax.get_ylim()[0], -1), 0,
                                 color="grey", alpha=0.3)
            else:
                x = np.linspace(*ax.get_xlim(), 10)
                y = np.linspace(*ax.get_ylim(), 10)
                X, Y = np.meshgrid(x, y)
                Z = np.zeros(X.shape)
                ax.plot_surface(X, Y, Z, color="grey", alpha=0.3)

            return self._plot_markers, self._plot_force_lines, self._plot_body_lines, self._plot_cp_lines

        if mode == "update":
            for i, (m, fl) in enumerate(zip(self._plot_markers, self._plot_force_lines)):
                tip = positions[i] + factor * forces[i]
                if case == "2D":
                    a0, a1 = non_zero_axes
                    m.set_data([positions[i, a0]], [positions[i, a1]])
                    fl.set_data([positions[i, a0], tip[a0]], [positions[i, a1], tip[a1]])
                else:
                    m.set_data([positions[i, 0]], [positions[i, 1]])
                    m.set_3d_properties(positions[i, 2])
                    fl.set_data([positions[i, 0], tip[0]], [positions[i, 1], tip[1]])
                    fl.set_3d_properties([positions[i, 2], tip[2]])

            for i, bl in enumerate(self._plot_body_lines):
                if case == "2D":
                    a0, a1 = non_zero_axes
                    bl.set_data([body_positions[i, a0], positions[i, a0]],
                                [body_positions[i, a1], positions[i, a1]])
                else:
                    bl.set_data([body_positions[i, 0], positions[i, 0]], [body_positions[i, 1], positions[i, 1]])
                    bl.set_3d_properties([body_positions[i, 2], positions[i, 2]])

            for cl, (i, j) in zip(self._plot_cp_lines, self._cp_line_pairs):
                if case == "2D":
                    a0, a1 = non_zero_axes
                    cl.set_data([positions[i, a0], positions[j, a0]],
                                [positions[i, a1], positions[j, a1]])
                else:
                    cl.set_data([positions[i, 0], positions[j, 0]], [positions[i, 1], positions[j, 1]])
                    cl.set_3d_properties([positions[i, 2], positions[j, 2]])
            return

        raise ValueError("Invalid mode. Must be 'init' or 'update'.")